# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u31zIzsX8fqmxM75X7uNDCPJE6W1vi4i
"""

#!/usr/bin/env python3
"""
corpus_manager.py
-----------------
Herramienta de gestión para el corpus de Weihnachtsansprachen alemanas.

Funciones:
  1. Normaliza nombres de archivo (corrige erratas, aplica convención estándar)
  2. Genera / actualiza CORPUS_METADATA.csv
  3. Muestra un resumen del estado del corpus

Convención de nombres:  {year}_{speaker_surname}_{genre}.txt
                        ej. 1962_adenauer_weihnachtsansprache.txt

Uso:
  python corpus_manager.py --dir ./speeches/adenauer
  python corpus_manager.py --dir ./speeches/adenauer --dry-run
  python corpus_manager.py --dir ./speeches --all-speakers
"""

import os
import re
import csv
import sys
import shutil
import hashlib
import argparse
from pathlib import Path
from datetime import datetime


# ---------------------------------------------------------------------------
# Configuración del corpus
# ---------------------------------------------------------------------------

GENRE = "weihnachtsansprache"

# Erratas conocidas en el género (variantes sin corrección)
GENRE_TYPOS = [
    "weihnachtsanprache",   # falta 's'
    "weihnachtsansprche",
    "weihnachtsanspache",
    "weihnachtsansprach",
    "weihnachtansprache",
]

# Roles conocidos por canciller/presidente y periodo
KNOWN_ROLES = {
    "adenauer": {
        "default": "Bundeskanzler",
        "years": range(1949, 1964),
    },
    "heuss": {
        "default": "Bundespräsident",
        "years": range(1949, 1960),
    },
    "luebke": {
        "default": "Bundespräsident",
        "years": range(1959, 1969),
    },
    "erhard": {
        "default": "Bundeskanzler",
        "years": range(1963, 1967),
    },
    "kiesinger": {
        "default": "Bundeskanzler",
        "years": range(1966, 1969),
    },
    "brandt": {
        "default": "Bundeskanzler",
        "years": range(1969, 1974),
    },
}

# Fecha canónica de los discursos (salvo que se sepa otra)
DEFAULT_DAY = "12-24"

METADATA_FIELDS = [
    "id", "speaker", "year", "date", "role",
    "filename", "word_count", "source", "notes", "transcription_status"
]


# ---------------------------------------------------------------------------
# Utilidades
# ---------------------------------------------------------------------------

def normalize_speaker(raw: str) -> str:
    """Extrae y normaliza el apellido del orador desde el nombre de archivo."""
    return raw.strip().lower()


def correct_genre(raw: str) -> str:
    """Corrige erratas conocidas en el nombre del género."""
    cleaned = raw.strip().lower()
    if cleaned in GENRE_TYPOS:
        return GENRE
    return cleaned


def parse_filename(filename: str) -> dict | None:
    """
    Intenta extraer año, orador y género de un nombre de archivo.
    Acepta múltiples formatos comunes:
      - 1962_adenauer_weihnachtsansprache.txt
      - Adenauer_Weihnachtanprache_1962.txt
      - adenauer_1962.txt
    Devuelve None si no puede extraer año y orador.
    """
    stem = Path(filename).stem.lower()
    parts = re.split(r"[ _\-]+", stem)

    year = None
    speaker = None
    genre_raw = None

    for part in parts:
        if re.fullmatch(r"\d{4}", part):
            year = int(part)
        elif part in KNOWN_ROLES:
            speaker = part
        elif part in GENRE_TYPOS or part == GENRE:
            genre_raw = part
        elif part.startswith("weihnacht"):
            genre_raw = part  # captura variantes no listadas

    if year is None or speaker is None:
        return None

    return {
        "year": year,
        "speaker": speaker,
        "genre_raw": genre_raw or GENRE,
    }


def canonical_filename(year: int, speaker: str) -> str:
    return f"{year}_{speaker}_{GENRE}.txt"


def count_words(filepath: Path) -> int:
    try:
        text = filepath.read_text(encoding="utf-8")
        return len(text.split())
    except Exception:
        return -1


def file_md5(filepath: Path) -> str:
    h = hashlib.md5()
    h.update(filepath.read_bytes())
    return h.hexdigest()


def get_role(speaker: str, year: int) -> str:
    info = KNOWN_ROLES.get(speaker)
    if info:
        return info["default"]
    return ""


def build_metadata_row(filepath: Path, parsed: dict) -> dict:
    year = parsed["year"]
    speaker = parsed["speaker"]
    return {
        "id": f"{speaker}_{year}",
        "speaker": speaker,
        "year": year,
        "date": f"{year}-{DEFAULT_DAY}",
        "role": get_role(speaker, year),
        "filename": canonical_filename(year, speaker),
        "word_count": count_words(filepath),
        "source": "",
        "notes": "",
        "transcription_status": "unverified",
    }


# ---------------------------------------------------------------------------
# Operaciones principales
# ---------------------------------------------------------------------------

def collect_txt_files(directory: Path) -> list[Path]:
    return sorted(directory.rglob("*.txt"))


def rename_file(old_path: Path, new_name: str, dry_run: bool = False) -> Path:
    new_path = old_path.parent / new_name
    if old_path.name == new_name:
        return old_path  # ya tiene el nombre correcto

    if dry_run:
        print(f"  [DRY-RUN] Renombrar: {old_path.name}  \u2192  {new_name}")
        return new_path

    if new_path.exists():
        print(f"  [AVISO] Ya existe {new_path}, no se renombra {old_path.name}")
        return old_path

    old_path.rename(new_path)
    print(f"  [OK] Renombrado: {old_path.name}  \u2192  {new_name}")
    return new_path


def load_existing_metadata(csv_path: Path) -> dict:
    """Carga el CSV existente como dict keyed por 'id'."""
    existing = {}
    if csv_path.exists():
        with open(csv_path, encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                existing[row["id"]] = row
    return existing


def write_metadata(csv_path: Path, rows: list[dict], dry_run: bool = False):
    if dry_run:
        print(f"\n  [DRY-RUN] Se escribir\u00eda CORPUS_METADATA.csv con {len(rows)} filas en {csv_path}")
        return

    rows_sorted = sorted(rows, key=lambda r: (r["speaker"], int(r["year"])))
    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=METADATA_FIELDS)
        writer.writeheader()
        writer.writerows(rows_sorted)
    print(f"\n  [OK] CORPUS_METADATA.csv actualizado \u2192 {csv_path}")


def process_directory(directory: Path, dry_run: bool = False) -> list[dict]:
    """
    Procesa todos los .txt de un directorio:
    renombra archivos con erratas y devuelve lista de filas de metadata.
    """
    files = collect_txt_files(directory)
    if not files:
        print(f"  [AVISO] No se encontraron archivos .txt en {directory}")
        return []

    rows = []
    skipped = []

    for filepath in files:
        parsed = parse_filename(filepath.name)
        if parsed is None:
            print(f"  [SKIP] No se puede parsear: {filepath.name}")
            skipped.append(filepath.name)
            continue

        # Corregir nombre si hay errata o no sigue la convención
        new_name = canonical_filename(parsed["year"], parsed["speaker"])
        final_path = rename_file(filepath, new_name, dry_run=dry_run)

        # Construir fila de metadata
        # Si dry_run, usamos la ruta original para contar palabras
        row = build_metadata_row(
            final_path if not dry_run else filepath,
            parsed
        )
        rows.append(row)

    if skipped:
        print(f"\n  [INFO] {len(skipped)} archivo(s) omitido(s) por nombre no reconocible:")
        for s in skipped:
            print(f"         - {s}")

    return rows


def print_summary(rows: list[dict]):
    if not rows:
        return
    print("\n" + "=" * 55)
    print(f"  RESUMEN DEL CORPUS  ({datetime.now().strftime('%Y-%m-%d')})")
    print("=" * 55)
    speakers = {}
    for r in rows:
        speakers.setdefault(r["speaker"], []).append(int(r["year"]))
    for sp, years in sorted(speakers.items()):
        years.sort()
        total_words = sum(
            r["word_count"] for r in rows
            if r["speaker"] == sp and r["word_count"] > 0
        )
        print(f"  {sp.capitalize():20s} {min(years)}\u2013{max(years)}"
              f"  ({len(years)} textos, {total_words:,} palabras)")
    print(f"\n  Total textos : {len(rows)}")
    print(f"  Total palabras: {sum(r['word_count'] for r in rows if r['word_count'] > 0):,}")
    print("=" * 55 + "\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv=None): # Added argv parameter
    parser = argparse.ArgumentParser(
        description="Gestión del corpus Weihnachtsansprachen"
    )
    parser.add_argument(
        "--dir", "-d",
        type=Path,
        required=True,
        help="Directorio ra\u00edz de los textos (ej. ./speeches/adenauer o ./speeches)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Simula operaciones sin modificar ni renombrar archivos"
    )
    parser.add_argument(
        "--all-speakers",
        action="store_true",
        help="Recorre todos los subdirectorios (un subdirectorio por orador)"
    )
    parser.add_argument(
        "--csv-out",
        type=Path,
        default=None,
        help="Ruta del CSV de metadata (por defecto: <dir>/CORPUS_METADATA.csv)"
    )
    return parser.parse_args(argv) # Passed argv to parse_args


def main():
    # Check if running in a Colab/Jupyter notebook environment
    if 'ipykernel' in sys.modules:
        # Provide default arguments suitable for Colab execution.
        # Based on the file list, text files like 'Adenauer_Weihnachtanprache_1954.txt' are directly in '/content/'.
        # So, we'll set the directory to the current working directory, which should be '/content/'.
        default_colab_args = ['--dir', './']
        args = parse_args(argv=default_colab_args)
    else:
        # Standard command-line execution, argparse will use sys.argv by default.
        args = parse_args()

    base_dir = args.dir.resolve()
    if not base_dir.exists():
        print(f"Error: el directorio '{base_dir}' no existe.")
        sys.exit(1)

    csv_out = args.csv_out or base_dir / "CORPUS_METADATA.csv"

    print(f"\nCorpus Weihnachtsansprachen \u2014 corpus_manager.py")
    print(f"Directorio: {base_dir}")
    print(f"Modo:       {'DRY-RUN (sin cambios)' if args.dry_run else 'ACTIVO'}\n")

    all_rows = []

    if args.all_speakers:
        # Cada subdirectorio es un orador
        subdirs = [d for d in sorted(base_dir.iterdir()) if d.is_dir()]
        if not subdirs:
            subdirs = [base_dir]
        for subdir in subdirs:
            print(f"\u2500\u2500 {subdir.name.upper()} \u2500\u2500")
            rows = process_directory(subdir, dry_run=args.dry_run)
            all_rows.extend(rows)
    else:
        all_rows = process_directory(base_dir, dry_run=args.dry_run)

    # Combinar con metadata existente (preserva campos como 'source' y 'notes')
    existing = load_existing_metadata(csv_out)
    merged = []
    for row in all_rows:
        rid = row["id"]
        if rid in existing:
            # Preservar campos editables manualmente
            for field in ("source", "notes", "transcription_status", "date", "role"):
                if existing[rid].get(field):
                    row[field] = existing[rid][field]
        merged.append(row)

    write_metadata(csv_out, merged, dry_run=args.dry_run)
    print_summary(merged)


if __name__ == "__main__":
    main()